apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-app # แยกชื่อออกมาให้ชัดเจน
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx-web
  template:
    metadata:
      labels:
        app: my-nginx-web
    spec:
      containers:
      - name: nginx-container
        image: my-nginx-web:latest # อิมเมจที่เรา build จาก Jenkins
        ports:
        - containerPort: 80